module.exports = {
    admin: 'ADMINISTRATOR ',
    kickMembers: 'KICK_MEMBERS',
    banMembers: 'BAN_MEMBERS',
    viewChannels: 'VIEW_CHANNEL',
    sendMessages: 'SEND_MESSAGES',
    manageMessages: 'MANAGE_MESSAGES',
    readHistoryNotActiveFor: 'READ_MESSAGE_HISTORY',
    mentionEveryone: 'MENTION_EVERYONE',
    useOutsideEmojis: 'USE_EXTERNAL_EMOJIS',
    connectToVoiceChannels: 'CONNECT',
    speakInVoiceChannels: 'SPEAK',
    muteUsersVoice: 'MUTE_MEMBERS',
    moveUsersBetweenChannels: 'MOVE_MEMBERS',
    manageEmojis: 'MANAGE_EMOJIS',
    changeNickname: 'CHANGE_NICKNAME',
    manageOthersNickname: 'MANAGE_NICKNAMES',
    manageRoles: 'MANAGE_ROLES',
    addReactions: 'ADD_REACTIONS',
    createInstantInvite: 'CREATE_INSTANT_INVITE',
    manageChannels: 'MANAGE_CHANNELS',
    manageServerInfo: 'MANAGE_GUILD',
};